### PR TITLE
/spas added

### PR DESCRIPTION
**Pull request by A-Gebrel**
not really much of changelog, added /spas for people who need it.

### CODE REVIEW

**Comment by khalidahmedshalabi** [comment]
Nice, this is actually needed. However there are a few things that have to be tweaked...
- You really don't need to use `GetPlayerName`, use `Player[playerid][Name]` or `Player[playerid][NameWithoutTag]` instead.
- Use 63 as a length for the first message and 77 for the second :stuck_out_tongue_winking_eye: (http://www.javascriptkit.com/script/script2/charcount.shtml). Oh yeah, why are you declaring the string outside the if statements when it's only used inside?
- I have a cool idea: how about forcing players who have spas to gunmenu selection when an admin disables spas? Would you enjoy scripting something like this? :smiley_cat: 
- I see that the AAD.db is changed; what have you actually changed in it?
- What would happen if the limit is greater than 1. For some weird reason this could happen, how would the script behave in such case? This should be considered because with your code, if spas limit is greater than 1 and /spas is used, it will still enable it (set to 1). I think this is better...

``` C++
if(GunmenuData[6][GunLimit] > 0)
{
// disable spas
}
else
{
// enable
}
```

**Comment by Whitetigerswt** [comment]
> Use 63 as a length for the first message

64, **(I wonder how many silly string errors you made in this gamemode trying to be "efficient")**

**Comment by A-Gebrel** [comment]
> You really don't need to use GetPlayerName, use Player[playerid][Name] or Player[playerid][NameWithoutTag] instead.

Never knew about this.
to be more accurate, didn't notice it.

> Use 63 as a length for the first message and 77 for the second :stuck_out_tongue_winking_eye:
> 11 is my name size, 24 is max. name size.
> [01:50:26] string length [string-11+24](disable) : 63
> [01:50:27] string length [string-11+24](enable) : 76
> so 64 and 77, ye.
> 
> I have a cool idea: how about forcing players who have spas to gunmenu selection when an admin disables spas? Would you enjoy scripting something like this? :smiley_cat:

Ye, why not.

I would really like to see that weird scenario -,- but ye will add it.

**Comment by A-Gebrel** [comment]
Alright, so added what you requested.

when spas is disabled, any player with spas will be sent to gunmenu again ( http://prntscr.com/7v20fe )
optimized the code as you requested.

**Comment by khalidahmedshalabi** [comment]
Alright, commit changes and sync?

**Comment by A-Gebrel** [comment]
Done

**Pull request closed without merging**
