### PR TITLE
Improvements (#2)

### PR DESCRIPTION
**Pull request by JamesCullum**
- /config now allows to set a password on all groups that needs to be entered when trying to spawn as this class. This allows the admin to force specific players to join a specific group and restricting random players joining teams.
- If weapons in the lobby are disabled, attacking in lobby in general is disabled as deathmatch obviously isnt intended.
- Rcon Login: Level change saving & error message fixed
- Lowered FPS minimum to 20 fps

Should be complete now, please test. Dont have my SSH key at the moment so i need to do all changes manually on the web.

### CODE REVIEW

**Comment by khalidahmedshalabi** [comment]
I like the group access thing, however there are somethings that need to be changed; for example, the texts and client messages aren't dynamic; you know what I mean? Like, it's always Alpha and Beta and if I have a TCW going on between 2 clans with different names, it's gonna be a little confusing. Here I'm talking about this chunk of code for instance, but not only this:

``` C++
new string[1700];
string = "";

if(strlen(GroupAccessPassword[0]) > 0) {
    strcat(string, "{FF6666}ALPHA");
} else {
    strcat(string, "{66FF66}ALPHA");
}

if(strlen(GroupAccessPassword[1]) > 0) {
    strcat(string, "\n{FF6666}BETA");
} else {
    strcat(string, "\n{66FF66}BETA");
}

if(strlen(GroupAccessPassword[2]) > 0) {
    strcat(string, "\n{FF6666}ALPHA SUB");
} else {
    strcat(string, "\n{66FF66}ALPHA SUB");
}

if(strlen(GroupAccessPassword[3]) > 0) {
    strcat(string, "\n{FF6666}BETA SUB");
} else {
    strcat(string, "\n{66FF66}BETA SUB");
}

if(strlen(GroupAccessPassword[4]) > 0) {
    strcat(string, "\n{FF6666}REFEREE");
} else {
    strcat(string, "\n{66FF66}REFEREE");
}
```

See? It doesn't matter what team names you set, the group names will always be Alpha, Beta, Referee. I think you got what I'm trying to say here now. You should change this. Perhaps you could check how the /switch command is done.

**Comment by JamesCullum** [comment]
Yeah i know what you mean, though i found it to be irrelevant as in the config settings the names have never been dynamic so far - one team is always called alpha/attacking or beta/defending.

**Comment by khalidahmedshalabi** [comment]
which should be changed too I think.

**Comment by khalidahmedshalabi** [comment]
but the code I posted earlier has to be changed at least.

**Comment by khalidahmedshalabi** [comment]
I think I can make some changes on my own!

**Pull request merged**
